### ISSUE TITLE
self.hander('hangup');

### ISSUE THREAD

**Issue by iatalmid** [tcncloud/agi-node#1]
Hello, 
I just simply used your example and what I can see after the caller hangs up:

/home/igor/work/899/node_modules/agi-node/lib/agi-server.js:31
      self.hander('hangup');
           ^
TypeError: undefined is not a function
    at AGIConnection.handleData (/home/igor/work/899/node_modules/agi-node/lib/agi-server.js:31:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

**Comment by iatalmid** [comment]
Strangely enough, after the update and even reinstall agi-node
I can see self.hander('hangup');
NP, I've fix this string manually.

But after fix I can see:

Exception in script [Error: hangup] Error: hangup
    at Future.resolve (/home/igor/work/899/node_modules/agi-node/node_modules/syncho/lib/Future.js:20:15)
    at AGIChannel.handleReply (/home/igor/work/899/node_modules/agi-node/lib/agi-channel.js:78:12)
    at AGIConnection.handleData (/home/igor/work/899/node_modules/agi-node/lib/agi-server.js:31:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

**Comment by sigxcpu76** [comment]
If the hangup happens during AGI execution this is normal. It is an attempt to mimic the exception thrown by asterisk-java library in the same circumstances.
