### ISSUE TITLE
Mapper multiple scripts

### ISSUE THREAD

**Issue by nicolascb** [tcncloud/agi-node#6]
it possible to map multiple scripts?

I tried this but it did not work:

```
function hello(channel) {
	console.log("hello")
  	console.log('Script got call %s -> %s', channel.request.callerid, channel.request.extension);
}

function bye(channel) {
        console.log("bye")
  	console.log('Script got call %s -> %s', channel.request.callerid, channel.request.extension);
}

/* 
	Start server 
*/
var server = new AGIServer({
    helloScript: hello,
    byeScript: bye
}, 4573);

exten => s,1,Agi(agi://localhost/helloScript)
exten => s,n,Agi(agi://localhost/byeScript)
```

Error:
```
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Could not find requested script)
    at AGIChannel.emit (events.js:163:17)
    at new AGIChannel (/opt/agi-server/node_modules/agi-node/lib/agi-channel.js:64:10)
    at AGIConnection.handleData (/opt/agi-server/node_modules/agi-node/lib/agi-server.js:46:21)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by sigxcpu76** [comment]
As far as I can see it should work. By the error displayed the ```mapper``` in ```agi-channel``` is empty (but not null).
In ```agi-server.js:46``` can you put a ```console.log``` on ```this.mapper``` to see its value?
A workaround is to initialize with a function an dispatch work from there.
